#!/usr/bin/env bash

set -exu

title=$1
kind=$2
base_directory="bradparker.com/usr/local/src/bradparker.com/site/content/"

case $kind in
  "note")
    directory="${base_directory}/notes"
    ;;
  *)
    directory="${base_directory}/posts"
    ;;
esac

cat > "${directory}/$(date --iso-8601)-$(echo "$title" | tr -d "," | tr " [:upper:]" "-[:lower:]").md" <<EOF
---
title: $title
---
EOF
