site: fd '.md|.css|.hs' {site,builder} | entr cabal new-run builder -- --input site --input $VENDOR_ASSETS --output dist-site
server: WEB_ROOT=dist-site cabal new-run server -- --protocol http --port 8080
