#!/usr/bin/env bash

set -exu

doctl compute droplet create \
  "bradparker.com" \
  --size s-1vcpu-3gb \
  --image ubuntu-16-04-x64 \
  --region sgp1 \
  --user-data "$(deployment/build-cloud-init)"
