#!/usr/bin/env bash

set -ex

doctl compute droplet create \
  "bradparker.com" \
  --size s-1vcpu-2gb \
  --image 70134260 \
  --ssh-keys "9e:f3:01:9e:e8:24:10:94:3b:2f:dc:4f:bf:73:42:9a" \
  --region sgp1
