#!/usr/bin/env bash

set -exuo pipefail

(
  cd $(dirname $BASH_SOURCE)
  rsync -va --no-owner --no-group host/ $1:host
  ssh -t $1 "sudo bash -c 'rsync -va --no-owner --no-group host/ / && nixos-rebuild switch'"
)
